name: Summarize Repository Activities
description: Summarize recent releases, pull requests, and issues of a repository

branding:
  icon: send
  color: white

inputs:
  model:
    description: The GitHub Model to use for summarization.
    required: false
    default: "openai/gpt-4o-mini"
  token:
    description: The GitHub token to use for summarization and fetching activities.
    required: true
  repository:
    description: |
      The repository to summarize.
      Format: `owner/repo`
    required: true

outputs:
  summary:
    description: The summary of the repository activities.

runs:
  using: node20
  main: dist/index.js
