name: Summarize Repository Activities
description: Summarize recent releases, pull requests, and issues of a repository

branding:
  icon: eye
  color: black

inputs:
  github-token:
    description: The GitHub token.
    required: false
    default: ${{ github.token }}
  locale:
    description: |
      The locale to use for summarization.
      Valid values: "ja", "en"
    required: false
    default: "en"
  days-ago:
    description: Target activities from the specified number of days ago.
    required: false
    default: "7"
  ai-model:
    description: The Model to use for summarization.
    required: false
    default: "openai/gpt-4o-mini"
  ai-api-endpoint:
    description: The API endpoint for the AI model.
    required: false
    default: "https://models.github.ai/inference/chat/completions"
  ai-api-key:
    description: The API key for the AI model.
    required: false
    default: ${{ github.token }}
  repository:
    description: |
      The repository to summarize.
      Format: `owner/repo`
    required: true
  releases-limit:
    description: The maximum number of releases to summarize.
    required: false
    default: "10"
  pull-requests-limit:
    description: The maximum number of pull requests to summarize.
    required: false
    default: "10"
  issues-limit:
    description: The maximum number of issues to summarize.
    required: false
    default: "10"
outputs:
  summary:
    description: The summary of the repository activities.
  has-new-release:
    description: Whether the repository has a new release.
  has-new-pull-request:
    description: Whether the repository has a new pull request.
  has-new-issue:
    description: Whether the repository has a new issue.
runs:
  using: node20
  main: dist/index.js
