name: Summarize Repository Activities
description: Summarize recent releases, pull requests, and issues of a repository

branding:
  icon: send
  color: white

inputs:
  ai-model:
    description: The Model to use for summarization.
    required: false
    default: "openai/gpt-4o-mini"
  ai-api-endpoint:
    description: The API endpoint for the AI model.
    required: false
    default: "https://models.github.ai/inference/chat/completions"
  ai-api-key:
    description: The API key for the AI model.
    required: false
    default: ${{ github.token }}
  repository:
    description: |
      The repository to summarize.
      Format: `owner/repo`
    required: true
  # TODO: limit

outputs:
  summary:
    description: The summary of the repository activities.

runs:
  using: node20
  main: dist/index.js
